Drop npm dependencies
akashic-games/akashic-cli-commons pull request #1
Opened 2017-02-21 05:18 UTC by kamakiri01

## このpull requestが解決する内容
node6, 7系でakashic-cliを利用すると正常に動作しません。
これは、新しいnodeが利用するnpmと、akashic-cli-commonsが依存しているnpmモジュールのバージョンが異なることが原因です。
よって、akashic-cli-commonsのnpmモジュール依存をやめ、execの利用に切り替えます。

## 破壊的な変更を含んでいるか?

 - PromisedNpm#setConfig()が削除されます。
 - PromisedNpm#ls()の挙動が変わります。node_modules以下にpackage.jsonに書かれていないモジュールがある場合、従来はpackage.jsonに従った結果を返しましたが、今後はエラーを返します。

2017-02-22 03:34 UTC, kamakiri01 commented on package.json
> +    "typescript": "^1.7.5",
akashic-cliのsemverに合わせました。

2017-02-22 03:36 UTC, kamakiri01 commented on src/PromisedNpm.ts
> +		});
この関数のみ挙動が変わります。

2017-02-22 03:37 UTC, kamakiri01 commented on src/PromisedNpm.ts
> +		});
この関数のみ挙動が変わります。

2017-02-22 03:58 UTC, xnv requested changes

2017-02-22 03:58 UTC, xnv commented on src/PromisedNpm.ts
> +			exec("npm ls --json --production --silent", (err: any, stdout: string, stderr: string) => {
引数 `silent: boolean` に応じて変化する必要はありませんか？

2017-02-22 03:58 UTC, xnv commented on src/PromisedNpm.ts
> +			exec("npm uninstall " + moduleNames.join(" "), (err: any) => {
- uninstall になっていますが update ではありませんか。ここはユニットテストだとモック化されてしまっていて直接テストされてないと思うので、動作確認は慎重にお願いしたいです。
- ここに限りませんが、 moduleNames の長さが 2 以上の時の動作確認がもしまだならお願いしたいです (`npm unlink module1 module2 ... moduleN` って動くんだっけ……とかそういうレベルの話です)。

2017-02-22 03:58 UTC, xnv commented on src/PromisedNpm.ts
> +		return new Promise<NpmLsRsultObject>((resolve, reject) => {
本件とまったく関係ありませんが `Rsult` になってるのでついでに修正をお願いしたいです……。

2017-02-22 04:17 UTC, kamakiri01 commented on src/PromisedNpm.ts
> +		return new Promise<NpmLsRsultObject>((resolve, reject) => {
commonとscanが利用しているので修正します…。

2017-02-22 04:18 UTC, kamakiri01 commented on src/PromisedNpm.ts
> +			exec("npm ls --json --production --silent", (err: any, stdout: string, stderr: string) => {
すみません、silent引数は利用者のscanで利用しています。対応します。

2017-02-22 04:30 UTC, kamakiri01 commented on src/PromisedNpm.ts
> +			exec("npm uninstall " + moduleNames.join(" "), (err: any) => {
- すみません明らかに記述ミスです。対応します。
- npmコマンドのうち  install/uninstall/link/unlink で同時に2つ以上のパッケージ名を使えることを確認しています。 例： `npm install @akashic/A @akashic/B @akashic/C`

2017-02-22 08:21 UTC, blackspotbear commented on spec/UtilSpec.js
> -			done();
`done()`を呼ばない時は`function (done)`の引数から`done`を除けないのでしょうか。

2017-02-22 08:21 UTC, blackspotbear commented on src/PromisedNpm.ts
> +						this._logger.error("Extraneous module found in node_modules. You must install modules Using akashic-cli.");
`Using` -> `using` かと思います。

2017-02-22 08:52 UTC, kamakiri01 commented on spec/UtilSpec.js
> -			done();
確かに未使用です。 除きます。

2017-02-22 08:52 UTC, kamakiri01 commented on src/PromisedNpm.ts
> +						this._logger.error("Extraneous module found in node_modules. You must install modules Using akashic-cli.");
直します。

2017-02-23 02:59 UTC, blackspotbear commented on spec/UtilSpec.js
> -			done();
あ、見落としていました。

2017-02-23 03:42 UTC, blackspotbear approved these changes

2017-02-23 08:34 UTC, xnv approved these changes

2017-02-24 06:17 UTC, merged