Hash dir name
akashic-games/akashic-cli-commons pull request #14
Opened 2018-06-11 10:17 UTC by kamakiri01

## このpull requestが解決する内容

変換時のファイル名ハッシュ化をディレクトリ名に対しても適用します。
また、TypeScriptの更新、typingsの削除を行います。

## 破壊的な変更を含んでいるか?

- なし

2018-06-18 08:39 UTC, kamakiri01 commented on src/Renamer.ts
> +			fsx.mkdirsSync(path.dirname(path.resolve(basedir, newFilePath)));
ハッシュ後のディレクトリ名が無い「かもしれない」ため fsx を使います。

2018-06-18 10:24 UTC, xnv requested changes

2018-06-18 10:24 UTC, xnv commented on src/Configuration.ts
> +				fs.accessSync(filePath, fs.constants.F_OK);
Node.js の v4 系サポート終了でこうなるのはいいのですが、  https://akashic-games.github.io/guide/akashic-cli.html のバージョン表記を追従したいです。

2018-06-18 10:24 UTC, xnv commented on src/Renamer.ts
> +		const hashedDirname = sha256(dirname).slice(0, dirname.length);
これ文字数が短いと恐ろしく衝突すると思います (ハッシュは16進数文字列でしょうから、1文字には16種類しかないので……)。素直にディレクトリ構造をなくしてしまいませんか。

2018-06-18 12:36 UTC, kamakiri01 commented on src/Renamer.ts
> +		const hashedDirname = sha256(dirname).slice(0, dirname.length);
`files` 以下に展開する形にしようと思います。

2018-06-18 12:36 UTC, kamakiri01 commented on src/Configuration.ts
> +				fs.accessSync(filePath, fs.constants.F_OK);
別途対応します。

2018-06-19 03:21 UTC, kamakiri01 commented on src/Renamer.ts
> +	return path.posix.join("files", hashedFilename + extname);
出力は `files` 以下に展開されます。

2018-06-19 04:26 UTC, xnv approved these changes
動作確認はしっかりやりたいですね。

2018-06-19 04:26 UTC, xnv commented on src/Renamer.ts
> + * 与えられたファイルパスのファイル名部分を、ファイルパスから計算したハッシュ値で置き換えたファイルパスを返す
説明を更新する必要があると思います。(特に `files/` 以下のパスにしてしまうことを明記したいです)

2018-06-19 04:26 UTC, xnv commented on src/Renamer.ts
> +
不要な空行ではありませんか。

2018-09-07 03:58 UTC, kamakiri01 commented
空ディレクトリ削除の対応が済んだのでこちらもマージします。

2018-09-07 04:02 UTC, merged