Remove empty dir when hash
akashic-games/akashic-cli-commons pull request #15
Opened 2018-07-05 12:53 UTC by kamakiri01

2018-07-17 11:08 UTC, xnv requested changes

2018-07-17 11:08 UTC, xnv commented on src/Renamer.ts
> +			return 0;
`assetDirs.sort((a, b) => (b.length - a.length))` と簡潔にできそうです。

2018-07-17 11:08 UTC, xnv commented on src/Renamer.ts
> +	});
_reanemGlobalScripts() のものと完全に同じ処理に見えるので、適当に関数に切り出しませんか。少なくとも  `removeDirectoryIfEmpty(dirpath: string): void` は作れそうな気がします。

2018-07-17 11:08 UTC, xnv commented on src/Renamer.ts
> +		const assetDirs = fs.readdirSync(path.resolve(basedir, "node_modules")).map((filepath) => path.join("node_modules", filepath));
これ、 node_modules だけ特別扱いされていますが、実際的には「 `assetDirs` に push される各ディレクトリから basedir までの各 "祖先ディレクトリ" 」を空ディレクトリ削除チェックの対象に加えればよいのではないでしょうか。というか、そうでないと

```
- a/
  - b/
    - c/
       - d.js
       - e.js
```

みたいなディレクトリ構造の時、 `a/b/` が (空にも関わらず) 残ってしまいそうな気がします。

2018-07-19 05:43 UTC, kamakiri01 commented on src/Renamer.ts
> +			return 0;
まとめます。

2018-07-19 05:43 UTC, kamakiri01 commented on src/Renamer.ts
> +	});
こちらもまとめます。

2018-07-19 05:44 UTC, kamakiri01 commented on src/Renamer.ts
> +		const assetDirs = fs.readdirSync(path.resolve(basedir, "node_modules")).map((filepath) => path.join("node_modules", filepath));
祖先ディレクトリのリストに対して削除チェックを通すようにします。

2018-07-23 07:55 UTC, xnv requested changes

2018-07-23 07:55 UTC, xnv commented on src/Renamer.ts
> +	return  Array.from(new Set(result));
`result` はここで組み立てているわけですから、最初から `result: Set<string>` で組み立てて最後に `Array.from()` する方が効率的ではありませんか。

2018-07-23 07:55 UTC, xnv commented on src/Renamer.ts
> +function listDirNamesFromBasedir(dirnames: string[], basedir: string): string[] {
- 渡された `basedir` が利用されていないようです。(lintは通っているでしょうか)
- 不要なら削ってよいのでは。もしそうなら関数名の `FromBaseDir` も削ることになりそうです。
- `listDirNames` 部分についても、「dirname を既に引数にとっておいて何を list するのか」イメージしにくいと思います。 `listAncestorDirNames` とかが実態を示唆する名前ではないでしょうか。

2018-07-23 07:55 UTC, xnv commented on src/Renamer.ts
> +		const dirFullPath = path.resolve(basedir, dirpath);
- `basedir` より上を間違って削除しないガードが欲しいです。 安全のためには `dirFullPath` を相対に戻して (`path.relative(basedir, dirFullPath)`) から `".."` で始まらないことを確認するべきではありませんか。(`dirpath` をチェックすることもできますが、 `dirpath` が正規化されていることに依存すべきではないので)
- 現実的には game.json あたりに阻まれて basedir より上を削除しにいく可能性は低いと思いますが、(空ディレクトリとはいえ)およそ「削除」は割と取り返しのつかない処理です。慎重になりたいです。
- その意味でこの関数には確実にテストが欲しいです。

2018-07-23 08:09 UTC, xnv commented on src/Renamer.ts
> +			if (files.length === 0) fs.rmdirSync(dirFullPath);
rmdir はディレクトリが空でなければどうせエラーなので、いきなり `rmdirSync()` して "EEXIST" や "ENOTEMPTY" を無視してもいいかもしれません。というか、 `readdirSync()` から `rmdirSync()` までの間に書き込みが走るケース (極めて稀ではあると思いますが) を考えたら EEXIST/ENOTEMPTY は握りつぶすべきでは。

2018-07-25 05:05 UTC, kamakiri01 commented on src/Renamer.ts
> +	return  Array.from(new Set(result));
最初からSetで組み立てるようにします。

2018-07-25 05:05 UTC, kamakiri01 commented on src/Renamer.ts
> +function listDirNamesFromBasedir(dirnames: string[], basedir: string): string[] {
lintが通っていないですね…akashic-cli-commons自体の問題のようなので別PRで対応します。

2018-07-25 05:06 UTC, kamakiri01 commented on src/Renamer.ts
> +		const dirFullPath = path.resolve(basedir, dirpath);
祖先を削除しないフィルタ・テスト追加します。

2018-07-25 14:36 UTC, kamakiri01 commented on src/Renamer.ts
> +export function removeDirectoryIfEmpty(dirnames: string[], basedir: string) {
実行上は不要ですがテストのためexportしています。

2018-07-26 04:40 UTC, xnv requested changes
全体的に、テストと動作確認を拡充したいです。少なくとも次のケースを確認する必要があると思います。

(1) 以下の構造のコンテンツを正しく rename し、不要なディレクトリ (特に script/ と script/a/) が残らないこと:

```
script/
 - a/
    - b/
       - c.js
 - d/
    - e.js
```

(2) removeDirectoryIfEmpty() に空でないディレクトリを与えた時、削除せずに正常終了すること
(3) removeDirectoryIfEmpty() に `["./script/", "./script/a/"]` のような引数を与えて、引数の順序に関わらず「最終的に中身が空になるディレクトリ」はすべて削除できること

2018-07-26 04:40 UTC, xnv commented on src/Renamer.ts
> +			if (["ENOENT", "EEXIST", "ENOTEMPTY"].indexOf(error.code) === -1) return;
これは……。

- 条件が逆ではありませんか。  "ENOENT" など「以外」を握りつぶしているように見えます。
- ↓のコードとやりたい処理が重複していそうにも見えます。
- 総じて、このパスを通過するテストが欲しいです。

2018-07-26 04:40 UTC, xnv commented on spec/RenamerSpec.js
> +			expect(() => {Renamer.removeDirectoryIfEmpty(["../ancestor/hoge.png"], "./srcDir")}).toThrow(new Error(Renamer.ERROR_PATH_INCLUDE_ANCESTOR));
動作しそうには見えますが、明らかにディレクトリ名を要求しているように見える "dirnames" という引数に、 "hoge.png" というまるでファイル名の引数を与えているのは紛らわしいように思います。

2018-07-26 04:40 UTC, xnv commented on src/Renamer.ts
> +	removeDirectoryIfEmpty(assetDirs, basedir);
こちらを `listAncestorDirNames()` にかける必要はないでしょうか。

2018-07-26 04:40 UTC, xnv commented on src/Renamer.ts
> +		const assetDirs = listAncestorDirNames(content.globalScripts);
引数が dirnames なのにファイルパスの集合である `globalScripts` を渡すんでしょうか。戻り値にはディレクトリパスだけでなくファイルパスが混入しそうに見えます。

これだと `readdirSync()` が ENOTDIR を投げるんじゃないかと思いますが、それが (EEXIST やらを握りつぶすべき箇所で) 間違って握りつぶされていて、一見動作しているっぽく見える、という謎の状態になっていることを危惧します。

2018-07-26 04:40 UTC, xnv commented on src/Renamer.ts
> +			if (files.length === 0) fs.rmdirSync(dirFullPath);
readdirSync() の確認なしでいきなり rmdirSync すればいいのでは。(「精神衛生上、空であることを確認してからにしたい」とかにはそれほど強く反対しません(まあ削除は怖いので)が、そうだとしてもどのみち完全ではありえない(からこそ↓でEEXISTとかをチェックする)わけで、少なくともこの確認が「気休め」であることをコメントで残す必要があると思います。)

2018-07-26 04:40 UTC, xnv commented on src/Renamer.ts
> +		while (currentDir.indexOf(path.sep) !== -1) {
絶対パスが与えられると無限ループになると思います。この関数の使われ方からは、そういう状況は起きなさそうですが、少なくともコメントとして注記される方がいいように思えます。同様に、 dirname に `../foo` みたいな normalize で消しきれない `..` が入り込んだ時も、たぶん意図しない動作になる気がします。

「不要なら消せばいいのでは」と申し上げたので何なんですが、こうなるくらいなら `basedir` を復活させて、  「`basedir` までの祖先ディレクトリを、 `basedir` からの相対パスで返す」という関数にする方がすっきりしそうな気がしてきます。

いずれにせよこの関数が引数に何を期待していて何を返すのか、関数の頭に簡単にコメントが欲しいです。(パス周りは特に akashic-cli の場合 unix パス固定だったり環境依存のパスだったり、相対だったり絶対だったり、どうしてもいろいろな前提が入り込むからです)

2018-07-26 04:40 UTC, xnv commented on src/Renamer.ts
> +export function removeDirectoryIfEmpty(dirnames: string[], basedir: string) {
テストのためだけに公開するなら、頭に `_` つけておくとかしませんか。 `NodeModules` あたりがそうなっているのではないかと思います。

2018-08-08 04:57 UTC, kamakiri01 commented on src/Renamer.ts
> +			if (files.length === 0) fs.rmdirSync(dirFullPath);
強い動機は無いので直します。

2018-08-08 04:57 UTC, kamakiri01 commented on src/Renamer.ts
> +		const assetDirs = listAncestorDirNames(content.globalScripts);
dirnameを渡すようにします。

2018-08-08 04:57 UTC, kamakiri01 commented on src/Renamer.ts
> +	removeDirectoryIfEmpty(assetDirs, basedir);
ありそうです。直します。

2018-08-08 04:57 UTC, kamakiri01 commented on spec/RenamerSpec.js
> +			expect(() => {Renamer.removeDirectoryIfEmpty(["../ancestor/hoge.png"], "./srcDir")}).toThrow(new Error(Renamer.ERROR_PATH_INCLUDE_ANCESTOR));
全体的にテストを再構成します。

2018-08-08 04:57 UTC, kamakiri01 commented on src/Renamer.ts
> +			if (["ENOENT", "EEXIST", "ENOTEMPTY"].indexOf(error.code) === -1) return;
うっ…直します。

2018-08-08 05:18 UTC, kamakiri01 commented on src/Renamer.ts
> +		while (currentDir.indexOf(path.sep) !== -1) {
コメント追加します。

2018-08-20 04:21 UTC, xnv requested changes

2018-08-20 04:21 UTC, xnv commented on README.md
> +**akashic-cli-commons** は [Akashic Engine](https://akashic-games.github.io/) で使われる、各 akahsic-cli-xxx コマンドの共通ライブラリです。
:+1:

2018-08-20 04:21 UTC, xnv commented on spec/RenamerSpec.js
> +					fs.statSync(ancestor);
例外が起きなかった時 (＝削除されておらず普通に stat に成功してしまった時) にもテストをパスしてしまいそうに見えます。 `statSync()` の直後に `done.fail()` を挟むべきではありませんか。

2018-08-20 04:21 UTC, xnv commented on spec/RenamerSpec.js
> +					fs.statSync(ancestor);
ここも。

2018-08-20 04:21 UTC, xnv commented on spec/RenamerSpec.js
> +			var ancestors = Renamer._listAncestorDirNames(["./srcDir/script/a/b/c.js", "./srcDir/script/d/e.js"]).reverse();
`.reverse()` はどういう意図による処理でしょうか。上のテストではこれを行わない箇所もありますが、意図どおりでしょうか。

2018-08-20 04:21 UTC, xnv commented on spec/RenamerSpec.js
> +			var ancestors = Renamer._listAncestorDirNames(["./srcDir/script/a/b/c.js", "./srcDir/script/d/e.js"]);
`_listAncestorDirNames()` に対するテストが欲しいです。このメソッドが例えば誤って空配列を返していたら、このテストも誤ってパスしてしまうからです。

2018-08-20 04:21 UTC, xnv commented on src/Renamer.ts
> +	const assetAncestorDirs = _listAncestorDirNames(assetDirs.map((filepath) => path.dirname(filepath)));
`assetDirs` に push する時点でディレクトリパスになっていると思いますが、

- もう一度 `dirname()` する必要はあるでしょうか
- 変数名は `dirpath` の方が適当ではありませんか

2018-08-20 04:21 UTC, xnv commented on src/Renamer.ts
> +	dirnames.forEach((dirpath) => {
`dirnames`  (ディレクトリ名群) の要素が `dirpath` (ディレクトリパス) なのは違和感があります。 `dirpaths` が適当ではありませんか。

2018-08-20 04:21 UTC, xnv commented on src/Renamer.ts
> +	dirnames.forEach((dirname) => {
ここも `dirname` になっていますが単なるディレクトリ名ではなくパスに見えます。

2018-08-20 04:30 UTC, xnv commented on spec/RenamerSpec.js
> +			var ancestors = Renamer._listAncestorDirNames(["./srcDir/script/a/b/c.js", "./srcDir/script/d/e.js"]).reverse();
追記: 理解しました、 not sorted を反映するんですね。しかし reverse することと sort されていないことの関係は外部仕様的には自明ではないと思います。コメントがあるとよいのではないでしょうか。

2018-08-20 04:37 UTC, xnv commented on spec/RenamerSpec.js
> +			var ancestors = Renamer._listAncestorDirNames(["./srcDir/script/a/b/c.js", "./srcDir/script/d/e.js"]);
……というか、` _removeDirectoryIfEmpty()` のテストと銘打っているユニットテストであるならば、それだけをテストする方がより健全ではありませんか。全体 (`renameAssetFilenames()`) のテストとは別に考えるべきに思えます。

2018-08-20 04:39 UTC, xnv commented on spec/RenamerSpec.js
> +					fs.statSync(ancestor);
これは何を確認するテストなのでしょうか。この箇所 (ディレクトリがあってもなくてもテストをパスしそう) の問題もあいまって目的が読み取れませんが……。

2018-08-31 04:16 UTC, kamakiri01 commented on src/Renamer.ts
> +	dirnames.forEach((dirname) => {
同じく直します。

2018-08-31 04:16 UTC, kamakiri01 commented on src/Renamer.ts
> +	dirnames.forEach((dirpath) => {
ですね…直します。

2018-08-31 04:16 UTC, kamakiri01 commented on src/Renamer.ts
> +	const assetAncestorDirs = _listAncestorDirNames(assetDirs.map((filepath) => path.dirname(filepath)));
確かに二重にdirnameしています。直します。

2018-08-31 04:16 UTC, kamakiri01 commented on spec/RenamerSpec.js
> +			var ancestors = Renamer._listAncestorDirNames(["./srcDir/script/a/b/c.js", "./srcDir/script/d/e.js"]);
`_listAncestorDirNames` と `_removeDirectoryIfEmpty` のテストは分離します。

2018-08-31 04:16 UTC, kamakiri01 commented on spec/RenamerSpec.js
> +			var ancestors = Renamer._listAncestorDirNames(["./srcDir/script/a/b/c.js", "./srcDir/script/d/e.js"]).reverse();
`_listAncestorDirNames` の挙動に依存しないかたちで書き直します。

2018-08-31 04:16 UTC, kamakiri01 commented on spec/RenamerSpec.js
> +					fs.statSync(ancestor);
同じく直します。

2018-08-31 04:16 UTC, kamakiri01 commented on spec/RenamerSpec.js
> +					fs.statSync(ancestor);
failで拾えるようにします。

2018-08-31 08:29 UTC, kamakiri01 commented on spec/RenamerSpec.js
> +					fs.statSync(ancestor);
failチェックしてませんでした。直します。

2018-08-31 10:12 UTC, kamakiri01 commented on src/Renamer.ts
> +		if (currentDir !== "..") result.add(currentDir);
やや苦しいですが、dirpaths に `./srcDir/script/**.*.js` を与えられたとき、normalizeによって `./` が消えてしまうケースを拾っています。

2018-09-05 06:20 UTC, xnv approved these changes
コメントつけましたが approved.

2018-09-05 06:20 UTC, xnv commented on spec/RenamerSpec.js
> +				'./srcDir/script/d/e',
長さ順でソートすると、同じ長さのものの順序がどうなるかは実装依存です。テストケースとしては辞書式順でソートするとかの方がよいのではないでしょうか。

2018-09-06 03:17 UTC, kamakiri01 commented on spec/RenamerSpec.js
> +				'./srcDir/script/d/e',
テストケース向けのソートに直します。

2018-09-07 03:40 UTC, kamakiri01 commented
テストが転んでいますが、node10系未対応のためによるものです。

2018-09-07 03:42 UTC, merged