指定されたコードがES5構文で書かれているかどうか判定する関数の追加
akashic-games/akashic-cli-commons pull request #17
Opened 2018-08-30 03:33 UTC by dera-

### 概要
* ブラウザ上で動作させるため、akashicコンテンツはスクリプトはES5構文で書かれている必要があるが、スクリプトがそうなっているかを判定する機能が現状ないので追加した

### やったこと
* 指定されたコードがES5構文で書かれているかどうか判定する関数の追加
* eslintの導入
* typescriptのバージョンアップ
  * バージョンアップしないとeslintを利用したコードがビルドできない状態だったため

2018-08-30 04:17 UTC, dera- commented
akashic-cli-commonsのテストコード上だと、eslintを利用した関数のテストをしようとすると`~/node_modules/eslint/lib/rules`は存在しない(実際は存在する)というエラーが発生し原因が不明なので一旦テストコードを削除しました。
一応、export-htmlやexport-zipではこの関数を利用している箇所のテストを書いているのでここで検証したいことは担保できていると思っていますが、それだけだと問題がある場合はテストコードを追加し原因を調査しようと思います。

2018-08-30 07:23 UTC, xnv requested changes

2018-08-30 07:23 UTC, xnv commented on src/LintUtil.ts
> +	return errors.length === 0;
これだと valid かどうかしか分からないので、どこがまずいか画面に出したいのですが、難しいでしょうか。(実際問題、自分がユーザだと考えてみたとき「どこが悪いのか」教えてくれないlinterはあまりにもつらいと思います)

2018-09-05 06:59 UTC, xnv commented on src/PromisedNpm.ts
> +			exec("npm ls --json --production" + (silent ? " --silent" : ""), (err: any, stdout: Buffer, stderr: Buffer) => {
このあたり、本題とは独立な変更のようですが、どういった背景によるものでしょうか。

2018-09-06 05:09 UTC, dera- commented on src/PromisedNpm.ts
> +			exec("npm ls --json --production" + (silent ? " --silent" : ""), (err: any, stdout: Buffer, stderr: Buffer) => {
コメントで補足するのを忘れていました、すみません。
こちら、ビルドを通すための修正です。execの第2引数のコールバック関数の引数の型はBufferである必要があったみたいです(実際のコードもそのように定義されていました)
ただ、1つ不思議なのはローカルではここ部分はビルド時に怒られずビルドが通ってたんですよね、nodeのバージョンの違いですかね？

2018-09-06 05:10 UTC, dera- commented on src/ConfigurationFile.ts
> +			fs.writeFile(confPath, text, {encoding: "utf8"}, (err: any) => {
こちらもtravis上でのビルドを通すための修正となります

2018-09-07 11:36 UTC, xnv approved these changes

2018-09-10 03:09 UTC, kamakiri01 approved these changes

2018-09-10 10:30 UTC, merged