skip requireing akashic-commons/node_modules
akashic-games/akashic-cli-commons pull request #3
Opened 2017-04-18 04:42 UTC by kamakiri01

## このpull equestが解決する内容
akashicコンテンツのdependenciesにbabel-polyfill が含まれている状態で `akashic scan globalScripts` を地用した際の挙動不良を解決します。

babel-polyfillは内部的に Node.processを呼び出しており、 globalScriptsが探索するrequireチェーンにNode.processを含んでしまいます。

## 破壊的な変更を含んでいるか?

2017-04-18 07:58 UTC, kamakiri01 commented on package.json
> +    "mock-fs": "~4.2.0",
node v7.7系でテストが通らなくなっていたので更新しました。動作はv4, v7.7で確認済。
https://github.com/tschaub/mock-fs/blob/master/changelog.md

2017-04-18 08:03 UTC, kamakiri01 commented on src/NodeModules.ts
> +					"akashic-cli-commons/node_modules/process/"
babel-polyfill のmainから参照される `import "regenerator-runtime/runtime";` の中で、 processを参照しているため、
rawFilePathに `../path/to/akashic-cli-commons/node_modules/process` へのパスが代入されます。
https://github.com/facebook/regenerator/blob/master/packages/regenerator-runtime/runtime.js#L192

2017-04-18 08:33 UTC, xnv requested changes

2017-04-18 08:33 UTC, xnv commented on src/NodeModules.ts
> +					].map((modulePath) => Util.makeUnixPath(modulePath));
- インデントがずれています。
- `makeUnixPath()` は必要でしょうか。この箇所は依存先が一つ見つかるたびに呼び出されます。もし `map` が必要ならこの関数の外で実行する方が望ましいと思います。(それでなくても外に出して良さそうですが)

2017-04-18 08:33 UTC, xnv commented on src/NodeModules.ts
> +					"akashic-cli-commons/node_modules/process/"
- 判定条件は妥当でしょうか。 my-original-akashic-cli-commons というモジュールがあったり、これと同じディレクトリ構造がたとえば script/ 以下にあると誤動作しそうに見えます
- この処理を追加する経緯はコード上にコメントが欲しいです。直接の対応理由は babel のなにがしかかもしれませんが、この対応そのものは babel と独立だと思います。
- `process` を特別扱いする理由はあるでしょうか。 akashic-cli-commons/node_modules/ 以下への依存はすべて無視する形でいいのではありませんか。
- 無視した時、「◯◯ (この例では process) への参照が検出された。(◯◯がコアモジュールの場合) Akashic コンテンツは Node.js のコアモジュールに依存してはならない。このコンテンツは正しく動作しない可能性がある」というような趣旨の警告を出しておきたいです。

2017-04-18 11:26 UTC, kamakiri01 commented on src/NodeModules.ts
> +					"akashic-cli-commons/node_modules/process/"
- `../` かつ `akashic-cli-commons/node_modules/` への参照を判定条件とします。
 - 経緯を追加します。babelに限らず、broserify中にNodeのコアメンバー呼ぶ場合を避けるための措置である旨を追記します。
 - 警告表示を追加します。
 -

2017-04-18 11:42 UTC, kamakiri01 commented on src/NodeModules.ts
> +					].map((modulePath) => Util.makeUnixPath(modulePath));
確かに不要な再定義になっています。直します。

2017-04-20 05:29 UTC, lambdataro approved these changes

2017-04-20 05:43 UTC, xnv requested changes

2017-04-20 05:43 UTC, xnv commented on src/NodeModules.ts
> +		// akashicコンテンツが 間接的に Node.js のコアモジュールを参照するモジュールに依存している場合、
細かい話ですが、「直接的に」コアモジュールを参照するモジュールに依存していても問題になりそうなので「間接的に」は不要ではないでしょうか。

2017-04-20 05:43 UTC, xnv commented on src/NodeModules.ts
> +		const ignoreModulePaths = ["akashic-cli-commons/node_modules/"];
https://github.com/akashic-games/akashic-cli-commons/pull/3#discussion_r111897212 で、"my-original-akashic-cli-commons" というモジュールがある場合についてコメントを書きましたが、対応されていますか。

2017-04-20 05:43 UTC, xnv commented on src/NodeModules.ts
> +						console.warn(msg);
`Logger` をオプション引数でとって使っていただきたいです。 `console.warn()` は `Logger` が渡されなかった時に限りたいです。

2017-04-20 06:49 UTC, kamakiri01 commented on src/NodeModules.ts
> +		// akashicコンテンツが 間接的に Node.js のコアモジュールを参照するモジュールに依存している場合、
直します。

2017-04-20 06:49 UTC, kamakiri01 commented on src/NodeModules.ts
> +		const ignoreModulePaths = ["akashic-cli-commons/node_modules/"];
`../` への参照がパスに含まれることを前提としたので、対応済です。

2017-04-20 06:50 UTC, kamakiri01 commented on src/NodeModules.ts
> +						console.warn(msg);
Logger対応します。別途 akashic-cli-scan にPRを出します。

2017-04-20 09:24 UTC, kamakiri01 commented
メッセージの修正を行いました。
また https://github.com/akashic-games/akashic-cli-scan/pull/10 で追従PRを作成しています。

2017-04-20 09:34 UTC, xnv approved these changes

2017-04-20 09:34 UTC, merged