add hashing filename function
akashic-games/akashic-cli-commons pull request #9
Opened 2017-12-21 05:51 UTC by kamakiri01

## このPullRequestが解決する内容
game.json のアセットファイル名をハッシュ化する処理 `Configuration#hashingAssetNames()` を追加します。

2017-12-21 09:52 UTC, yu-ogi commented
単体テスト欲しいです。

2017-12-21 10:27 UTC, xnv requested changes

2017-12-21 10:27 UTC, xnv commented on src/Util.ts
> +export function hashingBasenameInPath(filepath: string, nameLength: number): string {
- hashing だと名詞だと思います。全体的に hash でいいのではありませんか。
- basename と述べた時点で既に "InPath" の話でしょうし、 `path.basename()` との対応を考えても InPath は削れそうです。
- ついでに細かいんですが、 `nameLength` は最大値の話なら max という単語が入っているとより明快だと思います。

2017-12-21 10:27 UTC, xnv commented on src/Util.ts
> + * 与えられたファイルパスのハッシュをファイル名に置き換えたファイルパスを返す。
ファイル名(basename部分)「を」(ファイルパスから計算した)ハッシュ値「で」置き換えた文字列を返す、かと思います。

2017-12-21 10:27 UTC, xnv commented on src/Configuration.ts
> +	 * @param dest 出力先のgamejsonが置かれているパス
dest とされていますが、src でもあることが気になります。 他の箇所では `basedir` とか使っているので、会わせていただくとよいかもしれません。
https://github.com/akashic-games/akashic-cli-export-zip/blob/master/src/GameConfigurationUtil.ts#L52

2017-12-21 10:27 UTC, xnv commented on src/Configuration.ts
> +	hashingAssetNames(hashLength: number = 20, dest: string): void {
- 省略可能引数が先頭に来ていますが、意図通りでしょうか。個人的には引数順を逆にしたい気もします。(重要度の高い引数が先に来て欲しい)
- 「アセット名をハッシュ化する」というような名前に見えますが、実情とずれているように思えます。どちらかというと hashAssetPaths とかそういう感じなのではありませんか。

2017-12-21 10:27 UTC, xnv commented on src/Configuration.ts
> +		}
globalScripts の考慮をお願いしたいです。

2017-12-21 10:27 UTC, xnv commented on src/Util.ts
> +}
どこで使っているメソッドでしょうか。利用箇所がなければ一旦作らなくてよいのではありませんか。

2017-12-21 11:28 UTC, xnv requested changes

2017-12-21 11:28 UTC, xnv commented on src/Configuration.ts
> +			fs.renameSync(path.resolve(dest, filePath), path.resolve(dest, hashedFilePath));
`hashedFilePath` が衝突するケースの考慮が必要ではないでしょうか。

2017-12-22 01:20 UTC, yu-ogi commented on src/Configuration.ts
> +	 * アセットのファイル名をファイルパスに基づいてハッシュ化し、アセットファイル名をリネームしたうえで game.json に反映する
`Configuration` と `ConfigurationFile` の責務の区別がよくわからなくなっている気がします。
この関数では「自身のasset名をハッシュ化してリネームする（リネームは呼び出し元でしてしまうという手もありそう）」程度の役割に留めておき、その結果を `ConfigurationFile` で game.json に書き込む、という方が元のコードのポリシーに近いのではないでしょうか。

2017-12-22 06:30 UTC, kamakiri01 commented on src/Configuration.ts
> +	 * アセットのファイル名をファイルパスに基づいてハッシュ化し、アセットファイル名をリネームしたうえで game.json に反映する
この関数で更新された game.json の状態は、この関数終了時点ではまだファイル上の game.json に書き込まれていません。（オンメモリな GameConfiguration 型変数を弄っているだけです）
https://github.com/akashic-games/akashic-cli-export-zip/pull/6/files#r158259542 で指摘されたように、この関数自体をConfigurationに含めない方向で整合を取りたいと思います。

2017-12-22 06:30 UTC, kamakiri01 commented on src/Configuration.ts
> +			fs.renameSync(path.resolve(dest, filePath), path.resolve(dest, hashedFilePath));
衝突判定追加します。

2017-12-22 06:30 UTC, kamakiri01 commented on src/Util.ts
> +export function hashingBasenameInPath(filepath: string, nameLength: number): string {
- hashBasenameにします。
- max > 確かに。名前変えます。

2017-12-22 06:30 UTC, kamakiri01 commented on src/Util.ts
> + * 与えられたファイルパスのハッシュをファイル名に置き換えたファイルパスを返す。
直します。

2017-12-22 06:30 UTC, kamakiri01 commented on src/Util.ts
> +}
う、hashingBasenameInPathで利用する予定でしたが残っていたものです。

2017-12-22 06:30 UTC, kamakiri01 commented on src/Configuration.ts
> +		}
globalScripts 対応します。

2017-12-22 06:30 UTC, kamakiri01 commented on src/Configuration.ts
> +	hashingAssetNames(hashLength: number = 20, dest: string): void {
- 後から追加してそのままになっていたものなので、入れ替えます。
- アセット以外もハッシュ化するので hashFilePathsくらいにしてしまっても良い気がします。

2017-12-22 06:30 UTC, kamakiri01 commented on src/Configuration.ts
> +	 * @param dest 出力先のgamejsonが置かれているパス
basedir に直します。

2017-12-22 10:10 UTC, yu-ogi commented on src/Configuration.ts
> +	 * アセットのファイル名をファイルパスに基づいてハッシュ化し、アセットファイル名をリネームしたうえで game.json に反映する
であればコメントが誤っているのではないでしょうか。

2017-12-25 08:26 UTC, yu-ogi commented on src/Util.ts
> +import { GameConfiguration, OperationPluginDeclaration } from "./index";
内部モジュールなので `./GameConfiguration` から直接importしても良いのでは。

2017-12-25 08:40 UTC, yu-ogi commented on src/Util.ts
> + * アセット・globalScriptsのファイル名をファイルパスに基づいてハッシュ化し、アセットファイル名をリネームしたうえで game.json に反映する
- https://github.com/akashic-games/akashic-cli-commons/pull/9#discussion_r158462910 でもコメントいたしましたが、ここではgame.jsonには反映はしないのでは無いでしょうか。
 - このメソッドの名前と実装が剥離しているのが気になりました。
   - 名前的には「ファイルパスをハッシュする」
   - 実装は「アセット・globalScripts・operationPluginsをハッシュ化したファイルアセットに変換・リネームする」
     - 個人的には「アセットをハッシュ化＋リネームする」「globalScriptsをアセットに変換＋リネームする」「operationPluginsをアセットに変換＋リネームする」というように分割して、それを一つの処理としたメソッドを呼び出す、と言うかたちでも良さそうに思いました。
 - `content.moduleMainScript` の考慮は必要ないでしょうか。

2017-12-25 08:43 UTC, yu-ogi commented on src/Util.ts
> +		content.main = hashBasename(content.main, maxHashLength);
```
		content.main = content.assets[content.main].path
```
とかでは駄目ですかね？（再変換しているのが気になりました。）

2017-12-25 10:40 UTC, kamakiri01 commented on src/Configuration.ts
> +	 * アセットのファイル名をファイルパスに基づいてハッシュ化し、アセットファイル名をリネームしたうえで game.json に反映する
訂正します :bowing_man:

2017-12-25 10:42 UTC, kamakiri01 commented on src/Util.ts
> +import { GameConfiguration, OperationPluginDeclaration } from "./index";
そうですね。直します。

2017-12-25 11:57 UTC, kamakiri01 commented on src/Util.ts
> + * アセット・globalScriptsのファイル名をファイルパスに基づいてハッシュ化し、アセットファイル名をリネームしたうえで game.json に反映する
うっ、  `content.moduleMainScript` 漏れていました。ありがとうございます。
個人的には分割しなくても良いギリギリの規模かなと思っていますが、今やってしまうことに特に異議はありません。

ハッシュ化変換とファイルリネームを同時に処理する関数なので名づけが難しいですが、 renameAssetFilenames あたりが適当な名前でしょうか。

2017-12-25 12:10 UTC, kamakiri01 commented on src/Util.ts
> +		content.main = hashBasename(content.main, maxHashLength);
多分等価な結果が得られますが、次のコミットで関数分けたので再変換は許容しようと思います。

2017-12-26 01:42 UTC, yu-ogi commented on src/Util.ts
> + * 与えられたファイルパスのファイル名部分を、ファイルパスかた計算したハッシュ値で置き換えたファイルパスを返す。
`ファイルパスかた` -> `ファイルパスから`?

2017-12-26 01:47 UTC, yu-ogi commented on spec/UtilSpec.js
> +					path: Util.hashBasename("image/hoge.png", 20),
https://github.com/akashic-games/akashic-cli-commons/pull/9/files#diff-94fd024c5ed2cd52b0e58d87e7bd3dffR186
と等価なら `"image/a70844aefe0a5ceb64eb.png"` をそのまま比較しても良さそうに思いました。

2017-12-26 01:48 UTC, yu-ogi commented on src/Util.ts
> +		Object.keys(content.moduleMainScripts).forEach((name: string, idx: number) => {
(nits) このスコープでは `idx` いらないかな？と思いました。

2017-12-26 01:50 UTC, yu-ogi approved these changes
動作確認は出来ていませんが

2017-12-26 02:48 UTC, yu-ogi commented on src/Util.ts
> + * @param basedir 読み込んだ gamejson が置かれているパス
`@params` の更新も必要そうです。

2017-12-26 12:06 UTC, kamakiri01 commented on src/Util.ts
> + * 与えられたファイルパスのファイル名部分を、ファイルパスかた計算したハッシュ値で置き換えたファイルパスを返す。
うっ、その通りです。直します。

2017-12-26 12:06 UTC, kamakiri01 commented on spec/UtilSpec.js
> +					path: Util.hashBasename("image/hoge.png", 20),
ですね。テストに問題無さそうなのでそのまま文字列を使います。

2017-12-26 12:06 UTC, kamakiri01 commented on src/Util.ts
> +		Object.keys(content.moduleMainScripts).forEach((name: string, idx: number) => {
不要なので消します。

2017-12-26 12:07 UTC, kamakiri01 commented on src/Util.ts
> + * @param basedir 読み込んだ gamejson が置かれているパス
更新します。

2018-01-10 09:20 UTC, xnv requested changes

2018-01-10 09:20 UTC, xnv commented on src/Util.ts
> +}
この一連の差分、これだけ機能があったら一つのファイルい切り出していいのではありませんか (置き場のない小物をまとめておくのが util だと思うので)。

2018-01-10 09:20 UTC, xnv commented on src/Util.ts
> +	_reanmeModuleMainScripts(content, basedir, maxHashLength);
reanme が混じっています、というかむしろ reanme の方が多いですね……。

2018-01-10 09:20 UTC, xnv commented on src/Util.ts
> +function _renameFilename(basedir: string, filePath: string, hashedFilePath: string) {
- "rename" する関数が「 "hashed" ファイルパス」であることを知っている必要はないと思います。これは単に「既存ファイルを上書きしない rename()」とする方がより汎用性が高いのではないでしょうか。
- そうすると Error のメッセージで「 `Use other hash-filename param` 」とは書けなくなりますが、このようなメッセージは `renameAssetFilenames()` で与えればよいように思えます。

2018-01-10 09:20 UTC, xnv commented on src/Util.ts
> +			// あとで衝突判定する
このコメントがもし残るのであれば、「あとで」がどこなのか具体的なコメントが欲しいです (処理フロー的にあとなのか、TODOとしての「あとで」なのか読み取りにくいです)。「衝突判定は実際のリネーム時に行う」がもともと意図した内容でしょうか。

2018-01-10 09:20 UTC, xnv commented on src/Util.ts
> +	throw new Error(hashedFilePath + " is already exists. Use other hash-filename param.");
実際のリネーム中に衝突を検出したら諦めて Error にする、という処理フローに思えますが、中途半端に残ったファイルはどうなるのでしょうか。呼び出し元に削除する責務があるならその旨述べるべきに思えますし、そもそも実際にリネームする前に検出したいです。

2018-01-10 09:20 UTC, xnv commented on src/Util.ts
> +			// moduleMainScripts は globalScripts として登録されているためリネーム処理はしない
細かい話ですが "renameModuleMainScripts" という関数で「リネームはしない」と述べられているのは違和感があります。「ファイルのリネームはしない」ぐらいがより説明的ではありませんか。

2018-01-10 09:31 UTC, xnv commented on src/Util.ts
> +		content.main = hashBasename(content.main, maxHashLength);
`content.main` は require() にかけるパスなので、アセットIDをキーとして持っている `content.assets` から直接引くことはできないと思います。

2018-01-11 11:37 UTC, kamakiri01 commented on src/Util.ts
> +			// moduleMainScripts は globalScripts として登録されているためリネーム処理はしない
「ファイルの」リネームはしない、というコメントに改めます。

2018-01-11 11:37 UTC, kamakiri01 commented on src/Util.ts
> +			// あとで衝突判定する
コメント削除漏れです。
リネーム（または事前に）衝突判定をすべきというTODOを書き残したもので、 _renameFilename の acccessSync による判定がこれにあたります。

2018-01-11 11:37 UTC, kamakiri01 commented on src/Util.ts
> +	throw new Error(hashedFilePath + " is already exists. Use other hash-filename param.");
中途半端に生成されたファイル群は現状後始末されていない状態です。
事前に衝突判定を実リネーム中検出するのが多分正道ですが、ここは実リネーム中に検知した際はbasedirを削除する方向で対応します。

2018-01-11 11:37 UTC, kamakiri01 commented on src/Util.ts
> +function _renameFilename(basedir: string, filePath: string, hashedFilePath: string) {
hashedを省きます。
renameAssetFilenames以下でErrorを検知した際に、リネーム中のファイル群を削除しつつメッセージを出す方針で修正します。

2018-01-11 11:37 UTC, kamakiri01 commented on src/Util.ts
> +	_reanmeModuleMainScripts(content, basedir, maxHashLength);
う、typoです。。直します。

2018-01-11 12:30 UTC, kamakiri01 commented on src/Util.ts
> +	throw new Error(hashedFilePath + " is already exists. Use other hash-filename param.");
basedir の削除は renameAssetFilenames の読み出し元で実行します。

2018-01-12 03:47 UTC, kamakiri01 commented on src/Util.ts
> +}
Renamer モジュールに切り出します。

2018-01-12 10:05 UTC, yu-ogi commented on spec/UtilSpec.js
> +		it("hash game.json - throw error", function (done) {
これ、なにを確認するためのテストでしょう？
例外を投げる理由を示すようなコメントが欲しいです。

2018-01-14 14:24 UTC, kamakiri01 commented on spec/UtilSpec.js
> +		it("hash game.json - throw error", function (done) {
アセットのpathメンバが同一の場合、ファイル名衝突が発生するのでエラーになることを期待しています。
コメント追加します。

2018-01-15 03:56 UTC, yu-ogi commented on spec/RenamerSpec.js
> +			.catch(done.fail)
(nits) セミコロンが抜けていました。

2018-01-15 03:57 UTC, yu-ogi commented on spec/RenamerSpec.js
> +				expect(() => {Renamer.renameAssetFilenames(gamejson, "./srcDir")}).toThrow(new Error("Use other hash-filename param."));
(imo) 例外を投げたときに元のディレクトリ構造を壊していないか、というようなテストがあると良さそうに思いました。

2018-01-16 06:55 UTC, xnv requested changes

2018-01-16 06:55 UTC, xnv commented on src/Renamer.ts
> +		result = result && _renameFilename(basedir, mainPath, content.main);
`result &&` に意味があるでしょうか。

2018-01-16 06:55 UTC, xnv commented on src/Renamer.ts
> +		resultGlobalScripts = _renameGlobalScripts(content, basedir, maxHashLength);
エラーが発生していて失敗するのがわかっている状況でも最後まで続行するんでしょうか。

2018-01-16 06:55 UTC, xnv commented on src/Renamer.ts
> +		// all rename succeeded
これだったら else 節だけになるようにすればよいのではありませんか。このコメントを書いておきたいというモチベーションであれば理解できなくはないのですが、コメントの前に変数名を見直すのが先だと思います。

2018-01-16 06:55 UTC, xnv commented on src/Renamer.ts
> +		throw new Error("Use other hash-filename param.");
このエラーメッセージでユーザーに状況が伝わるでしょうか。

2018-01-16 06:55 UTC, xnv commented on src/Renamer.ts
> +		result = result && _renameFilename(basedir, filePath, hashedFilePath);
`false` を返せばいいと申し上げたのは私なので申し訳ないんですが、こういう形になとちょっと辛いですね……失敗した時に無駄な処理 (game.json 書き換えてもどうせ捨てるだけですよね) が多いですし、可読性的にも微妙に思えます (どう見ても大域脱出すべき処理を大域脱出なしで実現しているので、何か特別な意図があるように見えます)。ここまで複雑化するぐらいだったら、 衝突時はそれとわかる特別な値を投げる方がクリーンではないでしょうか。

2018-01-16 06:55 UTC, xnv commented on src/Renamer.ts
> +	var result = true;
一般論の私見ですが、 result ってあまりいい変数名でないことが多いような気がしています。それは「結果」であることしか意味しないからです。その「結果」がどういう意味なのか、可能ならその「意味」で名付ける方が親切な局面が多いように思えます。このケースでは succeeded/成功した ぐらいの名前がより明快ではないでしょうか。もちろんごく短い関数などで「丁寧に書くと名前が長くなりすぎる」みたいな時に、割りきって result という変数名を使うことは十分あるわけですが。

2018-01-16 12:39 UTC, kamakiri01 commented on spec/RenamerSpec.js
> +				expect(() => {Renamer.renameAssetFilenames(gamejson, "./srcDir")}).toThrow(new Error("Use other hash-filename param."));
例外の発生時に作業中のファイルを後処理する（削除する・移すなど）は、Renamerを呼び出す側の責務にしようと思っています。

2018-01-16 12:39 UTC, kamakiri01 commented on src/Renamer.ts
> +	var result = true;
これも私見になりますが、その関数がreturnする変数であることが変数名（result）から分かる、という点では可読性があるのではないかと思います。

2018-01-16 12:42 UTC, kamakiri01 commented on src/Renamer.ts
> +		result = result && _renameFilename(basedir, filePath, hashedFilePath);
失敗時の一連の処理については、失敗時点でthrowして処理を中断するようにします。

2018-01-17 06:41 UTC, xnv requested changes

2018-01-17 06:41 UTC, xnv commented on src/Renamer.ts
> +		throw error;
これだったら catch しなくていいのではありませんか。

2018-01-17 06:41 UTC, xnv commented on src/Renamer.ts
> +		var filePath = content.assets[name].path;
`const` でいいのではないでしょうか。

2018-01-17 07:02 UTC, kamakiri01 commented on src/Renamer.ts
> +		throw error;
う、確かに。直します

2018-01-17 07:03 UTC, kamakiri01 commented on src/Renamer.ts
> +		var filePath = content.assets[name].path;
これ既存と追加で var と const/let が混在してしまうんですが、このモジュール内は const/let 統一します。

2018-01-18 06:04 UTC, xnv approved these changes

2018-01-24 11:37 UTC, merged